# Generated by Django 4.0.5 on 2022-06-22 13:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('changapp', '0002_rename_cause_name_fundraiser_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='neighbourhood',
            new_name='fundraiser',
        ),
    ]
